### PR TITLE
Kennric/fix path

### PR DESCRIPTION
**Pull request by Kennric**
Double-quotes are needed for magic_shell_environment to properly set the path so that $PATH is interpolated instead of inserted as a literal.

### CODE REVIEW

**Comment by jordane** [comment]
@Kennric you might want to merge this into the develop branch.

**Comment by ramereth** [comment]
@jordane don't you mean rebase?

**Comment by jordane** [comment]
@ramereth No, @tschuy has been using the develop branch, which is why this pulls in a massive number of commits.

**Comment by tschuy** [comment]
Speaking of develop branch, can someone take a look at it? It's been sitting for a few weeks, I think it's ready to go.

**Comment by tschuy** [comment]
Merged into #2 as #7.

**Pull request closed without merging**
